name: Java CI

on:
  push:
    paths:
      - "src/"
      - "build.gradle"
      - "gradlew"
      - "gradlew.bat"
      - ".github/workflows/CI.yaml"

jobs:
  build:
    name: "Build - ${{ matrix.os }} - java-${{ matrix.java-version }}-${{ matrix.java-distribution }}"
    strategy:
      matrix:
        os:
          - "ubuntu-18.04"
          - "ubuntu-20.04"
          - "windows-2019"
          - "windows-2022"
          - "macos-11"
          - "macos-10.15"
        java-version:
          - "11"
          - "17"
        java-distribution:
          - "temurin"
          - "zulu"
          - "adopt-hotspot"
          - "adopt-openj9"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.java-version }}-${{ matrix.java-distribution }}"
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        shell: bash
        run: ./gradlew build
      - name: Build fat Jar with Gradle
        shell: bash
        run: ./gradlew shadowJar
